# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

services:

    proxy:
        image: caddy:latest
        volumes:
            - ./Caddyfile.gateway:/etc/caddy/Caddyfile:ro
            - /srv/caddy/sites.d:/etc/caddy/sites.d:ro
            - caddy_data:/data
            - caddy_config:/config
        networks: [gateway_net]
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
            - target: 443
              published: 443
              protocol: tcp
              mode: host
        deploy:
            replicas: 1
            restart_policy:
                condition: any

networks:
    gateway_net:
        driver: overlay
        attachable: true

volumes:
    caddy_data:
    caddy_config:
