// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

import { z } from "zod"

import { type BackupStatus, backupStatusSchema } from "./BackupStatus"

/** Identifier type for public.backup_records */
export type BackupRecordsId = string & { __brand: "BackupRecordsId" }

/** Represents the table public.backup_records */
export interface BackupRecordsTable {
	id: ColumnType<BackupRecordsId, BackupRecordsId | undefined, BackupRecordsId>

	filename: ColumnType<string, string, string>

	s3Key: ColumnType<string, string, string>

	sizeBytes: ColumnType<string | null, string | null, string | null>

	status: ColumnType<BackupStatus, BackupStatus | undefined, BackupStatus>

	error: ColumnType<string | null, string | null, string | null>

	startedAt: ColumnType<Date | null, Date | string | null, Date | string | null>

	completedAt: ColumnType<Date | null, Date | string | null, Date | string | null>

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>
}

export type BackupRecords = Selectable<BackupRecordsTable>

export type NewBackupRecords = Insertable<BackupRecordsTable>

export type BackupRecordsUpdate = Updateable<BackupRecordsTable>

export const backupRecordsIdSchema = z.string().uuid() as unknown as z.Schema<BackupRecordsId>

export const backupRecordsSchema = z.object({
	id: backupRecordsIdSchema,
	filename: z.string(),
	s3Key: z.string(),
	sizeBytes: z.string().nullable(),
	status: backupStatusSchema,
	error: z.string().nullable(),
	startedAt: z.date().nullable(),
	completedAt: z.date().nullable(),
	createdAt: z.date(),
	updatedAt: z.date(),
})

export const backupRecordsInitializerSchema = z.object({
	id: backupRecordsIdSchema.optional(),
	filename: z.string(),
	s3Key: z.string(),
	sizeBytes: z.string().optional().nullable(),
	status: backupStatusSchema.optional(),
	error: z.string().optional().nullable(),
	startedAt: z.date().optional().nullable(),
	completedAt: z.date().optional().nullable(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
})

export const backupRecordsMutatorSchema = z.object({
	id: backupRecordsIdSchema.optional(),
	filename: z.string().optional(),
	s3Key: z.string().optional(),
	sizeBytes: z.string().optional().nullable(),
	status: backupStatusSchema.optional(),
	error: z.string().optional().nullable(),
	startedAt: z.date().optional().nullable(),
	completedAt: z.date().optional().nullable(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
})
