// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

import { z } from "zod"

/** Identifier type for public.backup_config */
export type BackupConfigId = string & { __brand: "BackupConfigId" }

/** Represents the table public.backup_config */
export interface BackupConfigTable {
	id: ColumnType<BackupConfigId, BackupConfigId | undefined, BackupConfigId>

	enabled: ColumnType<boolean, boolean | undefined, boolean>

	intervalHours: ColumnType<number, number | undefined, number>

	retentionDays: ColumnType<number, number | undefined, number>

	notificationEmail: ColumnType<string | null, string | null, string | null>

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>

	updatedAt: ColumnType<Date, Date | string | undefined, Date | string>
}

export type BackupConfig = Selectable<BackupConfigTable>

export type NewBackupConfig = Insertable<BackupConfigTable>

export type BackupConfigUpdate = Updateable<BackupConfigTable>

export const backupConfigIdSchema = z.string().uuid() as unknown as z.Schema<BackupConfigId>

export const backupConfigSchema = z.object({
	id: backupConfigIdSchema,
	enabled: z.boolean(),
	intervalHours: z.number(),
	retentionDays: z.number(),
	notificationEmail: z.string().nullable(),
	createdAt: z.date(),
	updatedAt: z.date(),
})

export const backupConfigInitializerSchema = z.object({
	id: backupConfigIdSchema.optional(),
	enabled: z.boolean().optional(),
	intervalHours: z.number().optional(),
	retentionDays: z.number().optional(),
	notificationEmail: z.string().optional().nullable(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
})

export const backupConfigMutatorSchema = z.object({
	id: backupConfigIdSchema.optional(),
	enabled: z.boolean().optional(),
	intervalHours: z.number().optional(),
	retentionDays: z.number().optional(),
	notificationEmail: z.string().optional().nullable(),
	createdAt: z.date().optional(),
	updatedAt: z.date().optional(),
})
