// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { z } from "zod"

/** Represents the enum public.BackupStatus */
export enum BackupStatus {
	pending = "pending",
	in_progress = "in_progress",
	completed = "completed",
	failed = "failed",
}

/** Zod schema for BackupStatus */
export const backupStatusSchema = z.nativeEnum(BackupStatus)
