// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ActionConfigDefaultsTable } from "./ActionConfigDefaults"
import type { ActionInstancesTable } from "./ActionInstances"
import type { ActionRunsTable } from "./ActionRuns"
import type { ApiAccessLogsTable } from "./ApiAccessLogs"
import type { ApiAccessPermissionsTable } from "./ApiAccessPermissions"
import type { ApiAccessTokensTable } from "./ApiAccessTokens"
import type { AuthTokensTable } from "./AuthTokens"
import type { AutomationConditionBlocksTable } from "./AutomationConditionBlocks"
import type { AutomationConditionsTable } from "./AutomationConditions"
import type { AutomationRunsTable } from "./AutomationRuns"
import type { AutomationsTable } from "./Automations"
import type { AutomationTriggersTable } from "./AutomationTriggers"
import type { BackupConfigTable } from "./BackupConfig"
import type { BackupRecordsTable } from "./BackupRecords"
import type { CommunitiesTable } from "./Communities"
import type { CommunityMembershipsTable } from "./CommunityMemberships"
import type { FormElementsTable } from "./FormElements"
import type { FormElementToPubTypeTable } from "./FormElementToPubType"
import type { FormsTable } from "./Forms"
import type { InviteFormsTable } from "./InviteForms"
import type { InvitesTable } from "./Invites"
import type { InvitesHistoryTable } from "./InvitesHistory"
import type { MemberGroupsTable } from "./MemberGroups"
import type { MemberGroupToUserTable } from "./MemberGroupToUser"
import type { MembershipCapabilitiesTable } from "./MembershipCapabilities"
import type { MoveConstraintTable } from "./MoveConstraint"
import type { PrismaMigrationsTable } from "./PrismaMigrations"
import type { PubFieldSchemaTable } from "./PubFieldSchema"
import type { PubFieldsTable } from "./PubFields"
import type { PubFieldToPubTypeTable } from "./PubFieldToPubType"
import type { PubMembershipsTable } from "./PubMemberships"
import type { PubsTable } from "./Pubs"
import type { PubsInStagesTable } from "./PubsInStages"
import type { PubTypesTable } from "./PubTypes"
import type { PubValuesTable } from "./PubValues"
import type { PubValuesHistoryTable } from "./PubValuesHistory"
import type { SessionsTable } from "./Sessions"
import type { StageMembershipsTable } from "./StageMemberships"
import type { StagesTable } from "./Stages"
import type { UsersTable } from "./Users"

export interface PublicSchema {
	PubFieldSchema: PubFieldSchemaTable

	PubsInStages: PubsInStagesTable

	_FormElementToPubType: FormElementToPubTypeTable

	_MemberGroupToUser: MemberGroupToUserTable

	_PubFieldToPubType: PubFieldToPubTypeTable

	_prisma_migrations: PrismaMigrationsTable

	action_config_defaults: ActionConfigDefaultsTable

	action_instances: ActionInstancesTable

	action_runs: ActionRunsTable

	api_access_logs: ApiAccessLogsTable

	api_access_permissions: ApiAccessPermissionsTable

	api_access_tokens: ApiAccessTokensTable

	auth_tokens: AuthTokensTable

	automation_condition_blocks: AutomationConditionBlocksTable

	automation_conditions: AutomationConditionsTable

	automation_runs: AutomationRunsTable

	automation_triggers: AutomationTriggersTable

	automations: AutomationsTable

	backup_config: BackupConfigTable

	backup_records: BackupRecordsTable

	communities: CommunitiesTable

	community_memberships: CommunityMembershipsTable

	form_elements: FormElementsTable

	forms: FormsTable

	invite_forms: InviteFormsTable

	invites: InvitesTable

	invites_history: InvitesHistoryTable

	member_groups: MemberGroupsTable

	membership_capabilities: MembershipCapabilitiesTable

	move_constraint: MoveConstraintTable

	pub_fields: PubFieldsTable

	pub_memberships: PubMembershipsTable

	pub_types: PubTypesTable

	pub_values: PubValuesTable

	pub_values_history: PubValuesHistoryTable

	pubs: PubsTable

	sessions: SessionsTable

	stage_memberships: StageMembershipsTable

	stages: StagesTable

	users: UsersTable
}
