name: Promote from main

on:
    push:
        branches:
            - main

permissions:
    contents: read
    packages: write

jobs:
    ci:
        uses: ./.github/workflows/ci.yml

    build-all:
        needs: ci
        permissions:
            contents: read
            packages: write
        uses: ./.github/workflows/ghcr-build-all.yml
        secrets:
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        with:
            publish_latest: true

    run-e2e:
        needs:
            - ci
            - build-all
        uses: ./.github/workflows/e2e.yml

    deploy-docs:
        permissions:
            contents: write
            pages: write
            pull-requests: write
        uses: ./.github/workflows/build-docs.yml
        with:
            preview: false
